

PULP_OMP_APP = test


PULP_APP_OMP_SRCS = test.c


PULP_APP_OMP_SRCS += ../utility/misc.c
PULP_APP_OMP_SRCS += ../utility/tensor.c

PULP_APP_OMP_SRCS += ../model/model.c

PULP_APP_OMP_SRCS += ../layers/FirstLayer.c
PULP_APP_OMP_SRCS += ../layers/BinaryLayer.c
PULP_APP_OMP_SRCS += ../layers/LastLayer.c

PULP_CFLAGS = -O2 -g3

include $(PULP_SDK_HOME)/install/rules/pulp_rt.mk

